### ISSUE TITLE
Ices0 crashes when specifying folders instead of files in playlists

### ISSUE THREAD

**Issue by AlphaJack** [Moonbase59/ices0#2]
First of all, thank you for having updated Ices0 with a ton of useful features. 

I installed it on Arch ARM from the AUR: I modified the PKGBUILD to point the source to this repo and by changing its checksums.
On my small server I've got 5 streams of 320kbps mp3 (original bitrate of the files, no re-encoding when streaming) pointing to my icecast2 server. The CPU usage is almost non-existent, it doesn't even reach 4% with evertything running. 
Unfortunately I see that periodically one or two of the streams crashes. Some survives indefinitely, the configuration files are almost the same, except for the playlist files, the mountpoints and the descriptions. I get notified by systemd with the following (the stream has been online for a few minutes in this case, but the last time I checked it went offline just 2 seconds after being launched):
```
Sep 11 20:59:34 Jack-P2 audit[26445]: ANOM_ABEND auid=4294967295 uid=0 gid=0 ses=4294967295 pid=26445 comm="ices0" exe="/usr/bin/ices0" sig=11 res=1
Sep 11 20:59:34 Jack-P2 kernel: audit: type=1701 audit(1568228374.855:429): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=26445 comm="ices0" exe="/usr/bin/ices0" sig=11 res=1
Sep 11 20:59:35 Jack-P2 systemd[1]: Started Process Core Dump (PID 29051/UID 0).
-- Subject: A start job for unit systemd-coredump@5-29051-0.service has finished successfully
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- A start job for unit systemd-coredump@5-29051-0.service has finished successfully.
-- 
-- The job identifier is 11833.
Sep 11 20:59:35 Jack-P2 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@5-29051-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 11 20:59:35 Jack-P2 kernel: audit: type=1130 audit(1568228375.215:430): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@5-29051-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 11 20:59:35 Jack-P2 systemd-coredump[29055]: Removed old coredump core.ices0.0.ed399ee4cf084132a928a4e059cd749f.258.1567975660000000.lz4.
Sep 11 20:59:35 Jack-P2 systemd-coredump[29055]: Removed old coredump core.ices0.0.ed399ee4cf084132a928a4e059cd749f.11924.1567992468000000.lz4.
Sep 11 20:59:35 Jack-P2 systemd-coredump[29055]: Removed old coredump core.systemd-journal.0.ed399ee4cf084132a928a4e059cd749f.162.1568013171000000000000.lz4.
Sep 11 20:59:36 Jack-P2 systemd-coredump[29055]: Removed old coredump core.ices0.0.ed399ee4cf084132a928a4e059cd749f.16297.1568017802000000000000.lz4.
Sep 11 20:59:36 Jack-P2 systemd-coredump[29055]: Removed old coredump core.ices0.0.6f1890eab56b4e32a0cfa31166b2b923.235.1568071953000000000000.lz4.
Sep 11 20:59:36 Jack-P2 systemd-coredump[29055]: Removed old coredump core.ices0.0.6f1890eab56b4e32a0cfa31166b2b923.14796.1568133915000000000000.lz4.
Sep 11 20:59:36 Jack-P2 systemd-coredump[29055]: Removed old coredump core.ices0.0.6f1890eab56b4e32a0cfa31166b2b923.17222.1568142003000000000000.lz4.
Sep 11 20:59:36 Jack-P2 systemd-coredump[29055]: Removed old coredump core.ices0.0.6f1890eab56b4e32a0cfa31166b2b923.17772.1568146503000000000000.lz4.
Sep 11 20:59:36 Jack-P2 systemd-coredump[29055]: Removed old coredump core.ices0.0.6f1890eab56b4e32a0cfa31166b2b923.19952.1568165405000000000000.lz4.
Sep 11 20:59:43 Jack-P2 systemd-coredump[29055]: Process 26445 (ices0) of user 0 dumped core.
                                                 
                                                 Stack trace of thread 26445:
                                                 #0  0x000000007688f938 memcpy (libc.so.6)
                                                 #1  0x0000000000475204 n/a (ices0)
-- Subject: Process 26445 (ices0) dumped core
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
-- 
-- Process 26445 (ices0) crashed and dumped core.
-- 
-- This usually indicates a programming error in the crashing program and
-- should be reported to its vendor as a bug.
Sep 11 20:59:43 Jack-P2 systemd[1]: systemd-coredump@5-29051-0.service: Succeeded.
-- Subject: Unit succeeded
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- The unit systemd-coredump@5-29051-0.service has successfully entered the 'dead' state.
Sep 11 20:59:43 Jack-P2 kernel: audit: type=1131 audit(1568228383.745:431): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@5-29051-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 11 20:59:43 Jack-P2 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@5-29051-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
```

What other logs can I provide to find the culprit?

I've also noticed a few other bugs:
- Ices0 sometimes plays songs slower than the normal playback speed. I solve this issue by refreshing the page or the stream from the listening client
- Ices0 often skips to the next track before the song ends. I have checked the files and I can't understand why it doesn't play the whole song until the end

**Comment by AlphaJack** [comment]
I converted in bulk my files to mp3@320kbps, but rechecking them now I've noticed that something went wrong. Some of them are fine, others are cropped to weight 8.0 or 4.0 MB, others are just empty files. This would explain the "skipping to next track" problem. The culprit of the segmentation fault instead seems to be related to the presence of some folders in the playlists. 

Answering in order:
1. Raspberry Pi 2, Arch ARM 4.19.71-1
2. I could, but it doesn't seems necessary anymore
3. e-mail sent
4. I'm attaching the relevant parts, I've created a playlist of three elements:
```
chopped file.mp3
empty file.mp3
non existent file
folder/
```
This is the log that appears
```
# chopped files end normally:
[...]
DEBUG: Updated metadata on /test to: Dast - Let's You Go
DEBUG: Done sending

# empty files get skipped:
DEBUG: Builtin playlist handler serving: /usr/share/music/Techno/Slam - Vapour.mp3
DEBUG: Filename cleaned up from [/usr/share/music/Techno/Slam - Vapour.mp3] to [Slam - Vapour]
Error opening /usr/share/music/Techno/Slam - Vapour.mp3: Error reading header: /usr/share/music/Techno/Slam - Vapour.mp3

# non existent files get skipped:
DEBUG: Builtin playlist handler serving: /usr/share/music/Techno/Dast - Le
DEBUG: Filename cleaned up from [/usr/share/music/Techno/Dast - Le] to [Dast - Le]
Error opening /usr/share/music/Techno/Dast - Le: Error opening: No such file or directory

# folders cause a segmentation fault
DEBUG: Builtin playlist handler serving: /usr/share/music/
DEBUG: Filename cleaned up from [/usr/share/music/] to []
[1]    17403 segmentation fault  ices0 -c /usr/share/music/_icecast/test.xml
```
If I create a playlist of only chopped files the program runs as expected.
If I create a playlist of only empty or non existent files the program exits after 10 retries.
If I create a playlist of only folders the program crashes at the first try.

5. The slow playback speed problem seems to appear rarely, so I can't confirm any improvement with reecoding, although I believe it does solve this issue
6. This, I suppose, was the culprit
7. Builtin
8. Playlist are just text files containg the absolute path of the files
9. Files are at the moment on the same SD card of the OS
10. Local
11. [icecast 2.4.3-3](https://archlinuxarm.org/packages/armv7h/icecast)
12. Done
13. Done, multiple streams are ok
14. I could, but it doesn't seems necessary anymore
15. e-mail sent

Having said that, I would like to ask you if implementing these feature is feasible:
A. In a playlist, check if the line contains a file or a folder. If it's a folder, skip it
B. Option to select a folder and play recursively the files it contains. Is randomization possible in this case?
C. Do not print password in log. When launching the programs, the first lines say:
```
Logfile opened
DEBUG: Sending following information to libshout:
DEBUG: Stream: 0
DEBUG: Host: localhost:8000 (protocol: http)
DEBUG: Mount: /test, Password: XXXXXXXXX
```
D. AIFF reencoding support. Unlike FLAC those files are not compressed so I suppose the reecoding process require less power. Unlike WAV files, ID3v2 is largely used on AIFF ones. Is streaming @1411kbps possible?
E. The possibility to stream more tags (album artist, year, album artwork...), if Icecast doesn't prevent it
F. I use a script to caputure the PID when launching the files as daemons, is it necessary or Ices0 already creates its PIDfile?

**Comment by Moonbase59** [comment]
Thanks for helping and debugging!

If I understand correctly, some of your playlist entries are just folders, not actual music files?
This shouldn’t happen (at least it’s illegal for M3U/M3U8 playlists), but of course ices shouldn’t segfault in this case—I’ll look into that.

I don’t know how you create the playlists, if you’re using `find` you might want to add the `-type f` argument, i.e. `find . -type f -iname "*.mp3"`.

Responding to your questions:

A. I’ll look into that, simply skipping seems feasible.

B. Thats’s what playlists are for and can be handled much more elegantly by some external code, especially since playlists can be modified while ices is running (it will re-read the playlist in this case). We also have great scripting bindings (shell, Python, Perl) for letting ices know what to play.

   Introducing folder traversing within ices is currently not feasible, since
   * it breaks compatibility for other software that uses ices
   * it would require lots of code changes, i.e. the traversing logic, looking for "legal" filetypes, checking accessibility/readability of folders and files and much more.
   * it might introduce unwanted effects, like ices deciding to play 145,000 files before the next entry in the playlist comes up, just because your playlist entry accidentally pointed to the base of my music folder …

C. This is a good point for discussion. I have _very_ long and obscure passwords for my online (remote) Icecast and Shoucast servers, so I was always happy to be able to check these in the logs. It’s only shown when enabling the _verbose log_ (debug) which shouldn’t be used in a production environment anyway (since it’s _very_ verbose and quickly fills up disc space).

I can see your point, though, from a security standpoint. Let me think about it.

D. I’ll probably not have the resources to implement support for more file types into ices. There are so many things to be considered, I just found out when doing this for [loudgain](https://github.com/Moonbase59/loudgain). It could probably be done using a more "unified" file reader (like maybe libsndfile or the FFmpeg libraries) but this would require a major rewrite of ices.

E. I know that for instance Shoutcast 2 servers allow some more tag fields to be streamed, but the majority of broadcasting stations still use just one text string, containing only artist and title. This would also mean some kind of elaborate templating logic (i.e. how the user would wish the streaming title to built). It’s somehow a nice idea for an enhancement, but I won’t have the resources in the near future.

F. Ices will create its _log_, _cue_ and _pid_ file in the folder specified in `<BaseDirectory>…</BaseDirectory>` (within the `<Execution>…</Execution>` section of your `ices.conf`).

P.S.: For "extra" questions like B to F, it’s better to create extra issues, so they won’t go under. :-)

**Comment by Moonbase59** [comment]
I took the liberty to rename the issue since this seems to be the main culprit here.

**Comment by Moonbase59** [comment]
Try version **0.4.8**. This should fix trying to play non-regular files like devices or directories and skip them with an error message instead of segfaulting.
